### ISSUE TITLE
Release kss-node 2.0.0

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#154]
- [x] Support for preprocessor functions and mixins #22
- [x] Remove old --css option that copied CSS files into style guide #153
- [x] Add --css and --js options to include URLs of CSS/JS files #152
- [x] Prevent kss template styles from bleeding into styles being documented. #150
- [x] Stop relying on JavaScript to apply background color to template sidebar #151
- [x] Update demo source to use new 2.x features #155
- [x] Update docs to show 2.x features #156

**Comment by JohnAlbin** [comment]
#153 is the last API breaking change in the 2.x queue. The rest of the issues are API additions or bug fixes.

**Comment by JohnAlbin** [comment]
Drum roll, please.

**Comment by JohnAlbin** [comment]
```
> git checkout v2.0.0
> npm publish ./
> npm tag kss@2.0.0 next
```
