### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#166]
Must have:
- [x] ~~Get sample data from json file to load into markup block's Handlebars partials #133~~ _included with 2.0.2_
- [x] Allow templates to have a configuration file #164
- [x] Break bin/kss-node into reusable modules #138
- [x] Make name of styleguide.md configurable #84
- [x] Remove dots in {{referenceURI}} #174
- [x] {{modifier_class}} not displaying in sample code #167
- [x] Root sections with dashes don't appear in navigation #184
- [x] Prevent sections from appearing in wrong root sections #185
- [x] Allow mixed dashes and dots in style guide references #186

Very nice to have:
- [ ] Add responsive focus button for each section #165

**Comment by JohnAlbin** [comment]
Released the hound!
