### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#208]
Bugs:
- [x] #250 Generator 2.0 API lacks nodebacks
- [x] #193 If parent directories of destination don't exist, create them
- [x] #246 Add missing code coverage
- [x] #216 Section Generation Fails if "root level" of section is not documented

Bugs (cannot be reproduced):
- [ ] #137 Rangerror: Invalid array length

Bugs (edge case):
- [ ] #197 Generated Section 2 contains both Section 2 and Section 2n
- [ ] #204 Projects with mixed numbered/named references have missing sections

Features:
- [x] #212 Add --verbose option

Nice to haves:
- [ ] #139 Reference to source file and line where docblock was found?
- [ ] #165 Add responsive focus button for each section
- [ ] #175 Is it possible to control what level gets dedicated pages?
- [ ] #209 Improve sidebar navigation
- [x] #182 Give template ability to prepare itself or KssStyleguide before generate()
- [x] #251 Rename --init option to "clone" to better reflect its purpose

**Comment by JohnAlbin** [comment]
I'm going to roll a release even though I haven't met the features I wanted to add. The --verbose feature fixes a bug that some people were having and its quite nice.
