### ISSUE TITLE
3.0.0 priorities

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/kss-node#256]
The master branch is now where 3.x work will be done. I've branched a new 2.x for bugfixes against 2.4.x or for features that other people can't wait for and do a PR themselves. :-)

New features:
- [x] ~~Control which sections get dedicated pages #175~~  Postponed to post-3.0.0
- [x] Add responsive focus button for each section #165 
- [x] Generate a page for each item to aid visual regression tools #282 
- [x] Add Twig.js builder and class #272 
- [x] Allow --builder option to accept "builder/twig" #298 
- [x] Add Drupal 8 filters, functions and tags as Twig builder option #288 (basic implementation completed)
- [x] Rename public folder to "kss-assets" so KSS does not delete all files in public #176 
- [x] Reference to source file and line where docblock was found? #139 
- [x] Add --json option to output JSON of style guide #284 
- [x] Allow custom template for examples #189 
- [x] Add --markup option to toggle rendering of template for code sample #322
- [x] Add ability to hide/show HTML markup #363
- [x] Add toolbar button to show guide lines around examples #364

Improvements:
- [x] Show the section markup's file path #376
- [x] Twig builder should load JSON strings as Twig "safe strings" #321 
- [x] Rename kss-node CLI tool to kss #310 
- [ ] Refresh default template styling #273 
- [x] Missing reference to source file and line #300 
- [x] Convert Chai interface from should style to expect style #257 
- [x]  Add scrollspy to sidebar navigation #209 
- [x] Convert template's less to sass #247 
- [x] Update and simplify handlebars helpers #231 
- [x] Update to Handlebars 4.0 #244 
- [x] Change --xdemo option to just --demo #268 
- [x] Remove lt-ie\* classes from template's html element #296 
- [x] Error when scrolling: Cannot read property 'offsetTop' of null #362

API improvements:
- [ ] Separate parsing from style guide generation #365
- [x] Allow JSON file as --source input #374
- [x] Add source(), sourceFileName(), and sourceLine() to KssSection #368
- [x] Twig.js throws error when using kss in gulp watch task #305 
- [x] Drop support for Node.js 0.12 and update JavaScript syntax to ES6 (ECMAScript 2015) #262 
- [x] CLI module should use kss() function instead of the other way around #255 
- [x] Convert nodebacks to Promises #249
- [x] Rename KssStyleguide constructor to KssStyleGuide #224 
- [x] Rename options.multiline to options.header in traverse/parse #221 
- [x] Add method to return JSON of KssStyleGuide #190 
- [x] Add defaultValue() method to KssParameter #258 
- [x] Track custom property names in KssStyleGuide and KssSection #259 
- [x] Add 100% test coverage #267 
- [x] Remove typo-detection from section keywords #270 
- [x] Rename KssGenerator to KssBuilder to reduce confusion with ES6 generators #274 
- [x] Rename "templates" to be "builders" #275 
- [x] Merge KssConfig into KssBuilder #277 
- [x] Change "options" to "optionDefinitions" and "config" to "options" #279 
- [x] Upgrade eslint test linting to 2.x #281 
- [x] Allow KssBuilderHandlebars sub-classes to add to Handlebars context #285 
- [x] In Handlebars builder, change index.html to index.hbs #289
- [x] Change --helpers option to --extend #295

**Comment by JohnAlbin** [comment]
#365 is going to have to wait. I got a new job Jan 2017 using React.js and haven't used KSS since.

I apologize for not releasing 3.0.0 then, but it's released now.
