### ISSUE TITLE
Roadmap for 1.0.0, 2.0.0 and beyond

### ISSUE THREAD

**Issue by 0x6a68** [kss-node/kss-node#32]
hello together! since i am a big fan of kss and node, i have asked @hughsk to help him out as a contributor. as you have noticed i closed several issues and moved most of them into this list: 
- [x] Example Update, SASS projects
- [x] HTML Entities #30
- [x] Multiline Description for Modifiers #25 
- [x] Compass Sprite #24 
- [x] Support for functions and mixins #22 

if you have any features, which are not listed above, just leave a note here and we can discuss them. thanks and bye!
